image: gitpod/workspace-mongo
tasks:
  - init: yarn && yarn build
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - vscode-icons-team.vscode-icons@10.2.0:DrQUJPtFm0woSFiyitha8Q==
    - samuelcolvin.jinjahtml@0.12.0:lFI6zKplznEZPdWvFvRHwg==