name: Build
on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        yarn
        yarn build:production
    - uses: actions/upload-artifact@v1
      with:
        name: public
        path: public
    - uses: JS-DevTools/npm-publish@v1
      if: ${{ github.event_name == 'push' }}
      with:
        token: ${{ secrets.NPM_TOKEN }}
